// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns panel name and version.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Root endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Changes the password for the currently authenticated admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Change admin password",
                "parameters": [
                    {
                        "description": "Password change payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.changePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Logs in with username and password. Returns a JWT token, or temp_token + requires_totp if 2FA is enabled.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate admin",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "requires_totp with temp_token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/login/recovery": {
            "post": {
                "description": "Authenticates using a one-time recovery code (bypasses TOTP).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with recovery code",
                "parameters": [
                    {
                        "description": "Recovery login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.loginRecoveryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login/totp": {
            "post": {
                "description": "Completes 2FA login using the temp_token returned by /login and a TOTP code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Complete TOTP login",
                "parameters": [
                    {
                        "description": "TOTP login payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.loginTOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Clears the auth token cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated admin's profile without secrets.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current admin profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.meResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/totp/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Verifies the TOTP code and enables 2FA. Returns 8 one-time recovery codes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Confirm TOTP setup",
                "parameters": [
                    {
                        "description": "TOTP code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.confirmTOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/totp/disable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Disables 2FA. Requires a valid TOTP code or recovery code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Disable TOTP",
                "parameters": [
                    {
                        "description": "TOTP or recovery code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.disableTOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/totp/setup": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates a TOTP secret and returns a QR code URI for the admin to scan.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Initiate TOTP setup",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/clients": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "List clients",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by inbound ID",
                        "name": "inboundId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_transport_handler.clientDTO"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Create a client",
                "parameters": [
                    {
                        "description": "Client",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.createClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.clientDTO"
                        }
                    }
                }
            }
        },
        "/clients/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Get a client",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.clientDTO"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Update a client",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patch",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.updateClientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.clientDTO"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Delete a client",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/clients/{id}/links": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Get a client's share link and subscription URL",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.clientLinksDTO"
                        }
                    }
                }
            }
        },
        "/clients/{id}/reset-traffic": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Reset a client's traffic counters",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.clientDTO"
                        }
                    }
                }
            }
        },
        "/clients/{id}/status": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Set a client's status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.setStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.clientDTO"
                        }
                    }
                }
            }
        },
        "/core/config": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Preview the generated config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/core/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns lines from the sing-box log file with pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Core process logs",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Line offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 200,
                        "description": "Lines per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.coreLogsResponse"
                        }
                    }
                }
            }
        },
        "/core/reload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Renders config from the database, runs ` + "`" + `sing-box check` + "`" + `, installs it and reloads the core. A failed check returns 400 with the validation error and leaves the live config untouched.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Regenerate, validate and apply the config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/core/restart": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Restart the core",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/core/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates the initial config (if missing), then starts the core process.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Start the core",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/core/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Core process status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.coreStatusDTO"
                        }
                    }
                }
            }
        },
        "/core/stop": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Stop the core",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/core/version": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Core version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dashboard/metrics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Dashboard metrics snapshot",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.metricsDTO"
                        }
                    }
                }
            }
        },
        "/dashboard/traffic": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Recent throughput history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_transport_handler.trafficPointDTO"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns server health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/inbounds": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbounds"
                ],
                "summary": "List inbounds",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_transport_handler.inboundDTO"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbounds"
                ],
                "summary": "Create an inbound",
                "parameters": [
                    {
                        "description": "Inbound",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.inboundRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.inboundDTO"
                        }
                    }
                }
            }
        },
        "/inbounds/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbounds"
                ],
                "summary": "Get an inbound",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inbound ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.inboundDTO"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbounds"
                ],
                "summary": "Update an inbound",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inbound ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Inbound",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.inboundRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.inboundDTO"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbounds"
                ],
                "summary": "Delete an inbound",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inbound ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/inbounds/{id}/clone": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbounds"
                ],
                "summary": "Clone an inbound",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inbound ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.inboundDTO"
                        }
                    }
                }
            }
        },
        "/inbounds/{id}/toggle": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbounds"
                ],
                "summary": "Enable/disable an inbound",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inbound ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_handler.inboundDTO"
                        }
                    }
                }
            }
        },
        "/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns recent core and panel log lines from the in-memory ring buffer.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Recent log lines",
                "parameters": [
                    {
                        "type": "string",
                        "description": "info | warn | error",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "substring filter",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max lines (default 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_transport_handler.logEntryDTO"
                            }
                        }
                    }
                }
            }
        },
        "/subscription/{token}": {
            "get": {
                "description": "Returns the client's connection config. ?format=base64|plain|json (default base64).",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Fetch a subscription (public)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "base64 | plain | json",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_transport_handler.changePasswordRequest": {
            "type": "object",
            "properties": {
                "current_password": {
                    "type": "string",
                    "example": "oldpass"
                },
                "new_password": {
                    "type": "string",
                    "example": "newpass"
                }
            }
        },
        "internal_transport_handler.clientDTO": {
            "type": "object",
            "properties": {
                "expiry": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inboundId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "startAfterFirstUse": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "subscription": {
                    "type": "string"
                },
                "totalQuota": {
                    "type": "integer"
                },
                "usedDown": {
                    "type": "integer"
                },
                "usedUp": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "internal_transport_handler.clientLinksDTO": {
            "type": "object",
            "properties": {
                "link": {
                    "type": "string"
                },
                "subscription": {
                    "type": "string"
                }
            }
        },
        "internal_transport_handler.confirmTOTPRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "internal_transport_handler.coreLogsResponse": {
            "type": "object",
            "properties": {
                "hasMore": {
                    "type": "boolean"
                },
                "lines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_transport_handler.coreStatusDTO": {
            "type": "object",
            "properties": {
                "pid": {
                    "type": "integer"
                },
                "running": {
                    "type": "boolean"
                },
                "uptimeSeconds": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "internal_transport_handler.createClientRequest": {
            "type": "object",
            "properties": {
                "expiry": {
                    "type": "string"
                },
                "inboundId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "startAfterFirstUse": {
                    "type": "boolean"
                },
                "totalQuota": {
                    "type": "integer"
                }
            }
        },
        "internal_transport_handler.disableTOTPRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "internal_transport_handler.diskSegmentDTO": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "totalBytes": {
                    "type": "integer"
                },
                "usedBytes": {
                    "type": "integer"
                }
            }
        },
        "internal_transport_handler.inboundDTO": {
            "type": "object",
            "properties": {
                "clientCount": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "dest": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "protocol": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "settings": {
                    "$ref": "#/definitions/internal_transport_handler.inboundSettingsDTO"
                },
                "sni": {
                    "type": "string"
                },
                "tls": {
                    "type": "string"
                },
                "transmission": {
                    "type": "string"
                }
            }
        },
        "internal_transport_handler.inboundRequest": {
            "type": "object",
            "properties": {
                "acmeDomain": {
                    "type": "string"
                },
                "acmeEmail": {
                    "type": "string"
                },
                "certPath": {
                    "type": "string"
                },
                "dest": {
                    "type": "string"
                },
                "hy2BbrProfile": {
                    "type": "string"
                },
                "hy2BrutalDebug": {
                    "type": "boolean"
                },
                "hy2DownMbps": {
                    "type": "integer"
                },
                "hy2IgnoreClientBandwidth": {
                    "type": "boolean"
                },
                "hy2Masquerade": {
                    "type": "string"
                },
                "hy2Network": {
                    "type": "string"
                },
                "hy2ObfsMaxPacketSize": {
                    "type": "integer"
                },
                "hy2ObfsMinPacketSize": {
                    "type": "integer"
                },
                "hy2ObfsPassword": {
                    "type": "string"
                },
                "hy2UpMbps": {
                    "description": "Hysteria2.",
                    "type": "integer"
                },
                "keyPath": {
                    "type": "string"
                },
                "multiplexEnabled": {
                    "description": "VLESS multiplex.",
                    "type": "boolean"
                },
                "naiveNetwork": {
                    "description": "Naive.",
                    "type": "string"
                },
                "naiveQuicCongestionCtrl": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "protocol": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "sni": {
                    "type": "string"
                },
                "tls": {
                    "type": "string"
                },
                "transmission": {
                    "type": "string"
                }
            }
        },
        "internal_transport_handler.inboundSettingsDTO": {
            "type": "object",
            "properties": {
                "flow": {
                    "type": "string"
                },
                "grpcServiceName": {
                    "type": "string"
                },
                "hy2BbrProfile": {
                    "type": "string"
                },
                "hy2BrutalDebug": {
                    "type": "boolean"
                },
                "hy2DownMbps": {
                    "type": "integer"
                },
                "hy2IgnoreClientBandwidth": {
                    "type": "boolean"
                },
                "hy2Masquerade": {
                    "type": "string"
                },
                "hy2Network": {
                    "type": "string"
                },
                "hy2ObfsMaxPacketSize": {
                    "type": "integer"
                },
                "hy2ObfsMinPacketSize": {
                    "type": "integer"
                },
                "hy2ObfsPassword": {
                    "type": "string"
                },
                "hy2UpMbps": {
                    "description": "Hysteria2.",
                    "type": "integer"
                },
                "multiplexEnabled": {
                    "description": "VLESS multiplex.",
                    "type": "boolean"
                },
                "naiveNetwork": {
                    "description": "Naive.",
                    "type": "string"
                },
                "naiveQuicCongestionCtrl": {
                    "type": "string"
                },
                "publicKey": {
                    "type": "string"
                },
                "shortId": {
                    "type": "string"
                },
                "wsPath": {
                    "type": "string"
                }
            }
        },
        "internal_transport_handler.logEntryDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "t": {
                    "type": "integer"
                }
            }
        },
        "internal_transport_handler.loginRecoveryRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "1234-5678"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "internal_transport_handler.loginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "admin"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "internal_transport_handler.loginTOTPRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "temp_token": {
                    "type": "string",
                    "example": "eyJhbG..."
                }
            }
        },
        "internal_transport_handler.meResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_totp_enabled": {
                    "type": "boolean"
                },
                "totp_confirmed_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_transport_handler.metricsDTO": {
            "type": "object",
            "properties": {
                "coreRunning": {
                    "type": "boolean"
                },
                "coreVersion": {
                    "type": "string"
                },
                "cpu": {
                    "type": "number"
                },
                "diskSegments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_transport_handler.diskSegmentDTO"
                    }
                },
                "downloadBps": {
                    "type": "integer"
                },
                "inboundsActive": {
                    "type": "integer"
                },
                "monthBytes": {
                    "type": "integer"
                },
                "onlineNow": {
                    "type": "integer"
                },
                "ram": {
                    "type": "number"
                },
                "ramTotalBytes": {
                    "type": "integer"
                },
                "ramUsedBytes": {
                    "type": "integer"
                },
                "swap": {
                    "type": "number"
                },
                "swapTotalBytes": {
                    "type": "integer"
                },
                "swapUsedBytes": {
                    "type": "integer"
                },
                "todayBytes": {
                    "type": "integer"
                },
                "totalReceived": {
                    "type": "integer"
                },
                "totalSent": {
                    "type": "integer"
                },
                "totalUsers": {
                    "type": "integer"
                },
                "uploadBps": {
                    "type": "integer"
                },
                "uptimeSeconds": {
                    "type": "integer"
                }
            }
        },
        "internal_transport_handler.setStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_transport_handler.trafficPointDTO": {
            "type": "object",
            "properties": {
                "down": {
                    "type": "integer"
                },
                "t": {
                    "type": "integer"
                },
                "up": {
                    "type": "integer"
                }
            }
        },
        "internal_transport_handler.updateClientRequest": {
            "type": "object",
            "properties": {
                "expiry": {
                    "type": "string"
                },
                "inboundId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "startAfterFirstUse": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "totalQuota": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter \"Bearer \" followed by the JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "SingGrok API",
	Description:      "Local-first web panel for managing a sing-box process.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
